version: '2.1'

services:
  redis:
    image: redis

  celery:
    image: portfolio-work:latest
    command: celery worker -A app.celery
    environment:
      - REDIS_HOST=redis
    links:
      - redis

  portfolio-work:
    image: portfolio-work:latest
    build: .
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    links:
      - redis

    